version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/www:/www
      - /data/nginx/etc/conf.d:/etc/nginx/conf.d
      - /data/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/logs:/www/logs
      - /data/nginx/etc/html:/etc/nginx/html
      - /data/nginx/cert:/cert
    restart: unless-stopped
    privileged: true

# docker run -p 80:80 --name nginx -v /data/www:/www --privileged=true -v /data/nginx/etc/conf.d:/etc/nginx/conf.d -v /data/nginx/etc/nginx.conf:/etc/nginx/nginx.conf -v /data/nginx/logs:/www/logs -v /data/nginx/etc/html:/etc/nginx/html --rm nginx

